name: Publish Develop

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Restore with dotnet
      run: dotnet restore src/Blazui.Markdown/Blazui.Markdown.csproj --configfile $GITHUB_WORKSPACE/nuget.config
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
      with: 
        token: ${{secrets.github_token}}
    - name: pack nuget
      run: dotnet pack src/Blazui.Markdown/Blazui.Markdown.csproj /p:PackageVersion=0.0.1.${BUILD_NUMBER}-develop -c Release --no-build --no-restore
    - name: push nuget
      run: dotnet nuget push src/Blazui.Markdown/bin/Release/Blazui.Component.0.0.1.${BUILD_NUMBER}-develop.nupkg -s https://www.myget.org/F/wzxinchen-blazor/api/v2/package -k 2564e20d-4cd4-482e-ba4b-daf05e2effa8
